name: e2e
on:
  push:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: test output
        id: extract-image
        env:
          REF: ${{ github.ref }}
          JOB_NAME: ${{ github.ref == 'main' && 'post-eventing-manager-build' || 'release-eventing-manager-build' }}
        run: |
          echo "JOB_NAME=${JOB_NAME}"
          echo "REF=${REF}"
