name: e2e
on:
  pull_request:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: test output
        id: extract-image
        env:
          JOB_NAME: ${{ github.ref == 'main' && 'post-eventing-manager-build' || 'release-eventing-manager-build' }}
        run: |
          export IMAGE_NAME="docker.com"
          echo "JOB_NAME=${JOB_NAME}"
