name: pull-backend-switching

# Reference: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on:
  workflow_run:
    workflows: ["e2e"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    env:
      MANAGER_IMAGE: abs-${{ github.event.number }}
    steps:
      - name: 'hello'
        run: |
          echo "hello world: {MANAGER_IMAGE}"
